name: Build ESP32 Firmware

on:
  push:
    paths:
      - '*.ino'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - uses: arduino/setup-arduino-cli@v2

    - run: |

        arduino-cli core update-index

        arduino-cli core install esp32:esp32

    - run: |

        arduino-cli compile \
        --fqbn esp32:esp32:esp32 \
        main.ino

    - run: |

        mkdir output

        find . -name "*.bin" \
        -exec cp {} output/firmware.bin \;

    - uses: actions/upload-artifact@v4

      with:

        name: firmware

        path: output/firmware.bin
