name: Build ESP32 Firmware

on:
  push:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Arduino CLI
      uses: arduino/setup-arduino-cli@v2

    - name: Install ESP32 Core

      run: |

        arduino-cli core update-index

        arduino-cli core install esp32:esp32

    - name: Compile ESP32 Firmware

      run: |

        arduino-cli compile \
        --fqbn esp32:esp32:esp32 \
        --output-dir build \
        .

    - name: Show Build Files

      run: |

        ls -R build

    - name: Rename Firmware

      run: |

        cp build/*.ino.bin build/firmware.bin

    - name: Upload Firmware Artifact

      uses: actions/upload-artifact@v4

      with:

        name: firmware

        path: build/firmware.bin
